name: CI 30.1 Tests

on: [push, pull_request]

jobs:
  cypress-firefox-run:
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node16.14.2-slim-chrome100-ff99
      options: --user 1001

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests in Firefox
        run: npm run cy:run:firefox