name: CI Tests
on: [push, pull_request]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node-20.9.0-chrome-118.0.5993.88-1-ff-118.0.2-edge-118.0.2088.46-1
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests
        run: npx cypress run

  playwright-run:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.48.0-jammy
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          npm install
          npx playwright install --with-deps

      - name: Run Playwright tests
        run: npx playwright test --config playwright.config.mjs
